# Generated by Django 5.1.1 on 2024-10-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_mobile_number_alter_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, null=True)),
                ('monday_end', models.TimeField(blank=True, null=True)),
                ('monday_duty', models.CharField(blank=True, choices=[('Store Duty', 'Store Duty'), ('Cleaning Duty', 'Cleaning Duty')], max_length=100)),
                ('monday_day_off', models.BooleanField(default=False)),
                ('tuesday_start', models.TimeField(blank=True, null=True)),
                ('tuesday_end', models.TimeField(blank=True, null=True)),
                ('tuesday_duty', models.CharField(blank=True, choices=[('Store Duty', 'Store Duty'), ('Cleaning Duty', 'Cleaning Duty')], max_length=100)),
                ('tuesday_day_off', models.BooleanField(default=False)),
                ('wednesday_start', models.TimeField(blank=True, null=True)),
                ('wednesday_end', models.TimeField(blank=True, null=True)),
                ('wednesday_duty', models.CharField(blank=True, choices=[('Store Duty', 'Store Duty'), ('Cleaning Duty', 'Cleaning Duty')], max_length=100)),
                ('wednesday_day_off', models.BooleanField(default=False)),
                ('thursday_start', models.TimeField(blank=True, null=True)),
                ('thursday_end', models.TimeField(blank=True, null=True)),
                ('thursday_duty', models.CharField(blank=True, choices=[('Store Duty', 'Store Duty'), ('Cleaning Duty', 'Cleaning Duty')], max_length=100)),
                ('thursday_day_off', models.BooleanField(default=False)),
                ('friday_start', models.TimeField(blank=True, null=True)),
                ('friday_end', models.TimeField(blank=True, null=True)),
                ('friday_duty', models.CharField(blank=True, choices=[('Store Duty', 'Store Duty'), ('Cleaning Duty', 'Cleaning Duty')], max_length=100)),
                ('friday_day_off', models.BooleanField(default=False)),
                ('saturday_start', models.TimeField(blank=True, null=True)),
                ('saturday_end', models.TimeField(blank=True, null=True)),
                ('saturday_duty', models.CharField(blank=True, choices=[('Store Duty', 'Store Duty'), ('Cleaning Duty', 'Cleaning Duty')], max_length=100)),
                ('saturday_day_off', models.BooleanField(default=False)),
                ('sunday_start', models.TimeField(blank=True, null=True)),
                ('sunday_end', models.TimeField(blank=True, null=True)),
                ('sunday_duty', models.CharField(blank=True, choices=[('Store Duty', 'Store Duty'), ('Cleaning Duty', 'Cleaning Duty')], max_length=100)),
                ('sunday_day_off', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.employee')),
            ],
        ),
    ]
