# Generated by Django 5.1.1 on 2024-09-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
