# Generated by Django 5.1.1 on 2024-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_schedule_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duty',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('employee', 'day')},
        ),
    ]
