# Generated by Django 5.1.1 on 2024-10-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
