# Generated by Django 5.1.1 on 2024-10-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avg_price',
            new_name='avgPrice',
        ),
    ]
